# Generated by Django 5.0.2 on 2024-02-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('pleasant', models.BooleanField(verbose_name='приятная')),
                ('period', models.CharField(choices=[('daily', 'Ежеднево'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=15, verbose_name='период')),
                ('award', models.CharField(blank=True, max_length=255, null=True, verbose_name='награда')),
                ('run_time', models.IntegerField(verbose_name='время выполнения')),
                ('public', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
