# Generated by Django 5.0.2 on 2024-02-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежеднево'), ('weekly', 'Еженедельно')], default='daily', max_length=15, verbose_name='период'),
        ),
    ]
