# Generated by Django 5.0.2 on 2024-02-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(blank=True, choices=[('daily', 'Ежеднево'), ('weekly', 'Еженедельно')], default='daily', max_length=15, null=True, verbose_name='период'),
        ),
    ]
