# Generated by Django 5.0.2 on 2024-02-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_habit_place_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='run_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='время выполнения'),
        ),
    ]
