# Generated by Django 5.0.2 on 2024-02-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_habit_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='run_time',
            field=models.IntegerField(default=0, verbose_name='время выполнения'),
        ),
    ]
